# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  configure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: python:3.8-slim-buster

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install poetry and run poetry install
        run: |
          pip install poetry
          poetry install
  
  test:
    runs-on: ubuntu-latest
    container: python:3.8-slim-buster
    needs: configure
    steps:
      - name: Run tests
        run: poetry run python runtests.py
        
  build:
    runs-on: ubuntu-latest
    container: python:3.8-slim-buster
    needs: configure
    steps:
      - name: Build wheel
        run: poetry build
